[workspace]
members = [
    "plant-light",
    "pc-modem",
    "fleet-esb",
]

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = true
lto = true
codegen-units = 1
debug-assertions = true
